# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

name: Build conda package
on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.CONFIG }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - CONFIG: linux_64_gnuradio_extra_pin3.9.8numpy1.20python3.7.____cpython
            SHORT_CONFIG: linux_64_gnuradio_extra_pin3.9.8num_hdda782ed3a
            UPLOAD_PACKAGES: True
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
            os: ubuntu
          - CONFIG: linux_64_gnuradio_extra_pin3.9.8numpy1.20python3.8.____cpython
            SHORT_CONFIG: linux_64_gnuradio_extra_pin3.9.8num_hdc48805078
            UPLOAD_PACKAGES: True
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
            os: ubuntu
          - CONFIG: linux_64_gnuradio_extra_pin3.9.8numpy1.20python3.9.____cpython
            SHORT_CONFIG: linux_64_gnuradio_extra_pin3.9.8num_hb4ce3a6905
            UPLOAD_PACKAGES: True
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
            os: ubuntu
          - CONFIG: linux_64_gnuradio_extra_pin3.9.8numpy1.21python3.10.____cpython
            SHORT_CONFIG: linux_64_gnuradio_extra_pin3.9.8num_hb10c865f41
            UPLOAD_PACKAGES: True
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
            os: ubuntu
          - CONFIG: linux_64_gnuradio_extra_pinnumpy1.20python3.7.____cpython
            SHORT_CONFIG: linux_64_gnuradio_extra_pinnumpy1.2_h6ab1ce0c34
            UPLOAD_PACKAGES: True
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
            os: ubuntu
          - CONFIG: linux_64_gnuradio_extra_pinnumpy1.20python3.8.____cpython
            SHORT_CONFIG: linux_64_gnuradio_extra_pinnumpy1.2_hd42398e7dd
            UPLOAD_PACKAGES: True
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
            os: ubuntu
          - CONFIG: linux_64_gnuradio_extra_pinnumpy1.20python3.9.____cpython
            SHORT_CONFIG: linux_64_gnuradio_extra_pinnumpy1.2_hcf507074fb
            UPLOAD_PACKAGES: True
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
            os: ubuntu
          - CONFIG: linux_64_gnuradio_extra_pinnumpy1.21python3.10.____cpython
            SHORT_CONFIG: linux_64_gnuradio_extra_pinnumpy1.2_h42b1bbeabf
            UPLOAD_PACKAGES: True
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
            os: ubuntu
          - CONFIG: linux_aarch64_gnuradio_extra_pin3.9.8numpy1.20python3.7.____cpython
            SHORT_CONFIG: linux_aarch64_gnuradio_extra_pin3.9_h20bc28617c
            UPLOAD_PACKAGES: True
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
            os: ubuntu
          - CONFIG: linux_aarch64_gnuradio_extra_pin3.9.8numpy1.20python3.8.____cpython
            SHORT_CONFIG: linux_aarch64_gnuradio_extra_pin3.9_h18b88db687
            UPLOAD_PACKAGES: True
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
            os: ubuntu
          - CONFIG: linux_aarch64_gnuradio_extra_pin3.9.8numpy1.20python3.9.____cpython
            SHORT_CONFIG: linux_aarch64_gnuradio_extra_pin3.9_h4f7a3f0ef6
            UPLOAD_PACKAGES: True
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
            os: ubuntu
          - CONFIG: linux_aarch64_gnuradio_extra_pin3.9.8numpy1.21python3.10.____cpython
            SHORT_CONFIG: linux_aarch64_gnuradio_extra_pin3.9_hc5d9286a8a
            UPLOAD_PACKAGES: True
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
            os: ubuntu
          - CONFIG: linux_aarch64_gnuradio_extra_pinnumpy1.20python3.7.____cpython
            SHORT_CONFIG: linux_aarch64_gnuradio_extra_pinnum_hf8c4ed51ef
            UPLOAD_PACKAGES: True
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
            os: ubuntu
          - CONFIG: linux_aarch64_gnuradio_extra_pinnumpy1.20python3.8.____cpython
            SHORT_CONFIG: linux_aarch64_gnuradio_extra_pinnum_h2a1a06edca
            UPLOAD_PACKAGES: True
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
            os: ubuntu
          - CONFIG: linux_aarch64_gnuradio_extra_pinnumpy1.20python3.9.____cpython
            SHORT_CONFIG: linux_aarch64_gnuradio_extra_pinnum_hfafda91075
            UPLOAD_PACKAGES: True
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
            os: ubuntu
          - CONFIG: linux_aarch64_gnuradio_extra_pinnumpy1.21python3.10.____cpython
            SHORT_CONFIG: linux_aarch64_gnuradio_extra_pinnum_h63be9dad3d
            UPLOAD_PACKAGES: True
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
            os: ubuntu
          - CONFIG: linux_ppc64le_gnuradio_extra_pin3.9.8numpy1.20python3.7.____cpython
            SHORT_CONFIG: linux_ppc64le_gnuradio_extra_pin3.9_h4b910bc115
            UPLOAD_PACKAGES: True
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
            os: ubuntu
          - CONFIG: linux_ppc64le_gnuradio_extra_pin3.9.8numpy1.20python3.8.____cpython
            SHORT_CONFIG: linux_ppc64le_gnuradio_extra_pin3.9_h1a14ffaa6d
            UPLOAD_PACKAGES: True
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
            os: ubuntu
          - CONFIG: linux_ppc64le_gnuradio_extra_pin3.9.8numpy1.20python3.9.____cpython
            SHORT_CONFIG: linux_ppc64le_gnuradio_extra_pin3.9_h7fca3edc75
            UPLOAD_PACKAGES: True
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
            os: ubuntu
          - CONFIG: linux_ppc64le_gnuradio_extra_pin3.9.8numpy1.21python3.10.____cpython
            SHORT_CONFIG: linux_ppc64le_gnuradio_extra_pin3.9_h5f3d4ff279
            UPLOAD_PACKAGES: True
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
            os: ubuntu
          - CONFIG: linux_ppc64le_gnuradio_extra_pinnumpy1.20python3.7.____cpython
            SHORT_CONFIG: linux_ppc64le_gnuradio_extra_pinnum_h63e25c829e
            UPLOAD_PACKAGES: True
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
            os: ubuntu
          - CONFIG: linux_ppc64le_gnuradio_extra_pinnumpy1.20python3.8.____cpython
            SHORT_CONFIG: linux_ppc64le_gnuradio_extra_pinnum_h5237685a8d
            UPLOAD_PACKAGES: True
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
            os: ubuntu
          - CONFIG: linux_ppc64le_gnuradio_extra_pinnumpy1.20python3.9.____cpython
            SHORT_CONFIG: linux_ppc64le_gnuradio_extra_pinnum_h2a93c1732c
            UPLOAD_PACKAGES: True
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
            os: ubuntu
          - CONFIG: linux_ppc64le_gnuradio_extra_pinnumpy1.21python3.10.____cpython
            SHORT_CONFIG: linux_ppc64le_gnuradio_extra_pinnum_hf12c364f08
            UPLOAD_PACKAGES: True
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
            os: ubuntu
          - CONFIG: win_64_gnuradio_extra_pin3.9.8numpy1.20python3.7.____cpython
            SHORT_CONFIG: win_64_gnuradio_extra_pin3.9.8numpy_h3800f3a437
            UPLOAD_PACKAGES: True
            os: windows
          - CONFIG: win_64_gnuradio_extra_pin3.9.8numpy1.20python3.8.____cpython
            SHORT_CONFIG: win_64_gnuradio_extra_pin3.9.8numpy_h4d3e9ccc7c
            UPLOAD_PACKAGES: True
            os: windows
          - CONFIG: win_64_gnuradio_extra_pin3.9.8numpy1.20python3.9.____cpython
            SHORT_CONFIG: win_64_gnuradio_extra_pin3.9.8numpy_hb4896257a1
            UPLOAD_PACKAGES: True
            os: windows
          - CONFIG: win_64_gnuradio_extra_pin3.9.8numpy1.21python3.10.____cpython
            SHORT_CONFIG: win_64_gnuradio_extra_pin3.9.8numpy_ha8c124a778
            UPLOAD_PACKAGES: True
            os: windows
          - CONFIG: win_64_gnuradio_extra_pinnumpy1.20python3.7.____cpython
            SHORT_CONFIG: win_64_gnuradio_extra_pinnumpy1.20p_h5d44bd4765
            UPLOAD_PACKAGES: True
            os: windows
          - CONFIG: win_64_gnuradio_extra_pinnumpy1.20python3.8.____cpython
            SHORT_CONFIG: win_64_gnuradio_extra_pinnumpy1.20p_h866a645c44
            UPLOAD_PACKAGES: True
            os: windows
          - CONFIG: win_64_gnuradio_extra_pinnumpy1.20python3.9.____cpython
            SHORT_CONFIG: win_64_gnuradio_extra_pinnumpy1.20p_h7fd92f8ea6
            UPLOAD_PACKAGES: True
            os: windows
          - CONFIG: win_64_gnuradio_extra_pinnumpy1.21python3.10.____cpython
            SHORT_CONFIG: win_64_gnuradio_extra_pinnumpy1.21p_h6f454585b3
            UPLOAD_PACKAGES: True
            os: windows
          - CONFIG: osx_64_gnuradio_extra_pin3.9.8numpy1.20python3.7.____cpython
            SHORT_CONFIG: osx_64_gnuradio_extra_pin3.9.8numpy_h902842dd0b
            UPLOAD_PACKAGES: True
            os: macos
          - CONFIG: osx_64_gnuradio_extra_pin3.9.8numpy1.20python3.8.____cpython
            SHORT_CONFIG: osx_64_gnuradio_extra_pin3.9.8numpy_ha00e4f1bc5
            UPLOAD_PACKAGES: True
            os: macos
          - CONFIG: osx_64_gnuradio_extra_pin3.9.8numpy1.20python3.9.____cpython
            SHORT_CONFIG: osx_64_gnuradio_extra_pin3.9.8numpy_h9b9f0b0849
            UPLOAD_PACKAGES: True
            os: macos
          - CONFIG: osx_64_gnuradio_extra_pin3.9.8numpy1.21python3.10.____cpython
            SHORT_CONFIG: osx_64_gnuradio_extra_pin3.9.8numpy_hd31d50f21b
            UPLOAD_PACKAGES: True
            os: macos
          - CONFIG: osx_64_gnuradio_extra_pinnumpy1.20python3.7.____cpython
            SHORT_CONFIG: osx_64_gnuradio_extra_pinnumpy1.20p_hc83677ed8c
            UPLOAD_PACKAGES: True
            os: macos
          - CONFIG: osx_64_gnuradio_extra_pinnumpy1.20python3.8.____cpython
            SHORT_CONFIG: osx_64_gnuradio_extra_pinnumpy1.20p_hc1741b6262
            UPLOAD_PACKAGES: True
            os: macos
          - CONFIG: osx_64_gnuradio_extra_pinnumpy1.20python3.9.____cpython
            SHORT_CONFIG: osx_64_gnuradio_extra_pinnumpy1.20p_h2994ff05a5
            UPLOAD_PACKAGES: True
            os: macos
          - CONFIG: osx_64_gnuradio_extra_pinnumpy1.21python3.10.____cpython
            SHORT_CONFIG: osx_64_gnuradio_extra_pinnumpy1.21p_h40161402eb
            UPLOAD_PACKAGES: True
            os: macos
          - CONFIG: osx_arm64_gnuradio_extra_pin3.9.8numpy1.20python3.8.____cpython
            SHORT_CONFIG: osx_arm64_gnuradio_extra_pin3.9.8nu_he0be0d1ebe
            UPLOAD_PACKAGES: True
            os: macos
          - CONFIG: osx_arm64_gnuradio_extra_pin3.9.8numpy1.20python3.9.____cpython
            SHORT_CONFIG: osx_arm64_gnuradio_extra_pin3.9.8nu_h48cd735cd6
            UPLOAD_PACKAGES: True
            os: macos
          - CONFIG: osx_arm64_gnuradio_extra_pin3.9.8numpy1.21python3.10.____cpython
            SHORT_CONFIG: osx_arm64_gnuradio_extra_pin3.9.8nu_h8bff902584
            UPLOAD_PACKAGES: True
            os: macos
          - CONFIG: osx_arm64_gnuradio_extra_pinnumpy1.20python3.8.____cpython
            SHORT_CONFIG: osx_arm64_gnuradio_extra_pinnumpy1._h02180c118f
            UPLOAD_PACKAGES: True
            os: macos
          - CONFIG: osx_arm64_gnuradio_extra_pinnumpy1.20python3.9.____cpython
            SHORT_CONFIG: osx_arm64_gnuradio_extra_pinnumpy1._h4e43af7f7e
            UPLOAD_PACKAGES: True
            os: macos
          - CONFIG: osx_arm64_gnuradio_extra_pinnumpy1.21python3.10.____cpython
            SHORT_CONFIG: osx_arm64_gnuradio_extra_pinnumpy1._h84a6aaa9a3
            UPLOAD_PACKAGES: True
            os: macos
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Build on Linux
      if: matrix.os == 'ubuntu'
      env:
        CONFIG: ${{ matrix.CONFIG }}
        UPLOAD_PACKAGES: ${{ matrix.UPLOAD_PACKAGES }}
        DOCKER_IMAGE: ${{ matrix.DOCKER_IMAGE }}
        CI: github_actions
        UPLOAD_ON_BRANCH: conda
        BINSTAR_TOKEN: ${{ secrets.BINSTAR_TOKEN }}
      shell: bash
      run: |
        echo "::group::Configure binfmt_misc"
        docker run --rm --privileged multiarch/qemu-user-static:register --reset --credential yes
        export FEEDSTOCK_NAME="$(basename $GITHUB_REPOSITORY)"
        export GIT_BRANCH="$(basename $GITHUB_REF)"
        if [[ "${GITHUB_EVENT_NAME}" == "pull_request" ]]; then
          export IS_PR_BUILD="True"
        else
          export IS_PR_BUILD="False"
        fi
        echo "::endgroup::"
        ./.scripts/run_docker_build.sh

    - name: Build on macOS
      if: matrix.os == 'macos'
      env:
        CONFIG: ${{ matrix.CONFIG }}
        UPLOAD_PACKAGES: ${{ matrix.UPLOAD_PACKAGES }}
        CI: github_actions
        UPLOAD_ON_BRANCH: conda
        BINSTAR_TOKEN: ${{ secrets.BINSTAR_TOKEN }}
      shell: bash
      run: |
        export FEEDSTOCK_NAME="$(basename $GITHUB_REPOSITORY)"
        export GIT_BRANCH="$(basename $GITHUB_REF)"
        if [[ "${GITHUB_EVENT_NAME}" == "pull_request" ]]; then
          export IS_PR_BUILD="True"
        else
          export IS_PR_BUILD="False"
        fi
        ./.scripts/run_osx_build.sh

    - name: Install Miniconda for windows
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniforge-version: latest
        miniforge-variant: Mambaforge
      if: matrix.os == 'windows'
    - name: Build on windows
      shell: cmd
      run: |
        call activate base
        mamba.exe install -c conda-forge 'python=3.9' conda-build conda pip boa conda-forge-ci-setup=3
        if errorlevel 1 exit 1
        setup_conda_rc .\ ".\.conda/recipe" .\.ci_support\%CONFIG%.yaml
        if errorlevel 1 exit 1
        

        if EXIST LICENSE.txt (
          copy LICENSE.txt ".conda/recipe\\recipe-scripts-license.txt"
        )
        conda.exe mambabuild ".conda/recipe" -m .ci_support\%CONFIG%.yaml
        if errorlevel 1 exit 1
        set "FEEDSTOCK_NAME=%GITHUB_REPOSITORY:*/=%"
        set "GIT_BRANCH=%GITHUB_REF:refs/heads/=%"
        if /i "%GITHUB_EVENT_NAME%" == "pull_request" (
          set "IS_PR_BUILD=True"
        ) else (
          set "IS_PR_BUILD=False"
        )
        if /i "%UPLOAD_PACKAGES%" == "true" (
          if /i "%IS_PR_BUILD%" == "false" (
            upload_package  .\ ".\.conda/recipe" .ci_support\%CONFIG%.yaml
          )
        )
      env:
        PYTHONUNBUFFERED: 1
        CONFIG: ${{ matrix.CONFIG }}
        CI: github_actions
        UPLOAD_PACKAGES: ${{ matrix.UPLOAD_PACKAGES }}
        UPLOAD_ON_BRANCH: conda
        BINSTAR_TOKEN: ${{ secrets.BINSTAR_TOKEN }}
      if: matrix.os == 'windows'
    - name: Prepare conda build artifacts
      id: prepare-artifacts
      shell: bash
      if: ${{ always() }}
      env:
        CONFIG: ${{ matrix.CONFIG }}
        SHORT_CONFIG: ${{ matrix.SHORT_CONFIG }}
        OS: ${{ matrix.os }}
      run: |
        export CI=github_actions
        export CI_RUN_ID=$GITHUB_RUN_ID
        export FEEDSTOCK_NAME="$(basename $GITHUB_REPOSITORY)"
        export ARTIFACT_STAGING_DIR="$GITHUB_WORKSPACE"
        if [ $OS == "macos" ]; then
          export CONDA_BLD_DIR="${MINIFORGE_HOME:-${HOME}/miniforge3}/conda-bld"
        elif [ $OS == "windows" ]; then
          export CONDA_BLD_DIR="${CONDA//\\//}/conda-bld"
        else
          export CONDA_BLD_DIR="build_artifacts"
        fi
        # Archive everything in CONDA_BLD_DIR except environments
        # Archive the CONDA_BLD_DIR environments only when the job fails
        # Use different prefix for successful and failed build artifacts
        # so random failures don't prevent rebuilds from creating artifacts.
        JOB_STATUS="${{ job.status }}"
        if [ $JOB_STATUS == "failure" ]; then
          export BLD_ARTIFACT_PREFIX="conda_artifacts"
          export ENV_ARTIFACT_PREFIX="conda_envs"
        else
          export BLD_ARTIFACT_PREFIX="conda_pkgs"
        fi
        ./.scripts/create_conda_build_artifacts.sh
      continue-on-error: true

    - name: Store conda build artifacts
      uses: actions/upload-artifact@v2
      if: ${{ always() && steps.prepare-artifacts.outcome == 'success' }}
      with:
        name: ${{ steps.prepare-artifacts.outputs.BLD_ARTIFACT_NAME }}
        path: ${{ steps.prepare-artifacts.outputs.BLD_ARTIFACT_PATH }}
        retention-days: 14
      continue-on-error: true

    - name: Store conda build environment artifacts
      uses: actions/upload-artifact@v2
      if: ${{ failure() && steps.prepare-artifacts.outcome == 'success' }}
      with:
        name: ${{ steps.prepare-artifacts.outputs.ENV_ARTIFACT_NAME }}
        path: ${{ steps.prepare-artifacts.outputs.ENV_ARTIFACT_PATH }}
        retention-days: 14
      continue-on-error: true